#!/bin/bash

  #This is the main script that will handle most communication between all of the various scripts.
  
  $FILEDIR='cat /srv/minecraft/configuration/filedir'
  $SCRIPTDIR='cat /srv/minecraft/configuration/scriptdir'
  
  case "$1" in
	log)
		# Logs
		sh "$SCRIPTDIR/logger" $2 $3
		echo "Sent to logger."
		fi
		;;
	help|--help|-h)
		echo "Usage: $0 COMMAND"
		echo
		echo "Available commands:"
		echo -e "   start \t\t Starts the server"
		echo -e "   stop \t\t Stops the server"
		echo -e "   kill \t\t Kills the server"
		echo -e "   restart \t\t Restarts the server"
		echo -e "   reload \t\t Reloads the server configuration"
		echo -e "   backup \t\t Backups the worlds defined in the script"
		echo -e "   whole-backup \t Backups the entire server folder"
		echo -e "   check-update \t Checks for updates of $CB_JAR and $MC_JAR"
		echo -e "   update \t\t Fetches the latest version of minecraft.jar server and Bukkit"
		echo -e "   log-roll \t\t Moves and compresses the logfiles"
		echo -e "   log \t\t\t Prints the server log"
		echo -e "   to-disk \t\t Copies the worlds from the ramdisk to worldstorage"
		echo -e "   save-off \t\t Flushes the world to disk and then disables saving"
		echo -e "   save-on \t\t Re-enables saving if it was previously disabled by save-off"
		echo -e "   say \t\t\t Prints the given string to the ingame chat"
		echo -e "   connected \t\t Lists connected users"
		echo -e "   playercount \t\t Prints the number of connected users"
		echo -e "   status \t\t Displays server status"
		echo -e "   version \t\t Displays Bukkit version and then exits"
		echo -e "   links \t\t Creates nessesary symlinks"
		echo -e "   last \t\t Displays recently connected users"
		echo -e "   worlds \t\t Displays a list of available worlds"
		echo -e "   ramdisk WORLD \t Toggles ramdisk configuration for WORLD"
		echo -e "   overviewer WORLD \t Creates a map of the WORLD with Minecraft-Overviewer"
		echo -e "   whitelist \t\t Prints the current whitelist"
		echo -e "   whitelist-add NAME \t Adds the specified player to the server whitelist"
		echo -e "   whitelist-reload \t Reloads the whitelist"
		echo -e "   screen \t\t Shows the server screen"
		;;
	*)
		echo "No such command, see $0 help"
		exit 1
		;;
esac

exit 0
