#!/bin/bash

  #This is the main script that will handle most communication between all of the various scripts.
  
  $FILEDIR='cat /srv/minecraft/configuration/filedir'
  $SCRIPTDIR='cat /srv/minecraft/configuration/scriptdir'
  
  case "$1" in
	log)
		# Logs
		sh "$SCRIPTDIR/logger" $2 $3
		echo "Sent to logger."
		fi
		;;
	logrotate)
		sh "$SCRIPTDIR/logrotate" $2 $3
		;;
	*)
	logarchive
		echo "No such command, see $0 help"
		exit 1
		;;
esac

exit 0
